### ISSUE TITLE
Type error with "String.includes"

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion-module-extron-smp351#10]
This error seems to be appearing on log-in in the latest builds.

![Screen Shot 2020-03-03 at 8 11 11 AM](https://user-images.githubusercontent.com/50299051/75784349-b4675500-5d27-11ea-9a8f-01c3e8fc7072.png)

I wonder if it's related to this changed
`else if (self.login === true && data.includes("Inf36*")) {`
to
`else if (self.login === true && data.includes(/Inf36*/)) {`
in commit https://github.com/bitfocus/companion-module-extron-smp351/commit/f62969b9350e1e50e47e86e14911d3a812878c83

**Comment by EventReplay** [comment]
@bryce-seifert as recommended by @haakonnessjoen I changed all data.match to a regular expression not string maybe I shouldn't have changed the data.includes?

**Comment by bryce-seifert** [comment]
Resolved with https://github.com/bitfocus/companion-module-extron-smp351/pull/11
