### ISSUE TITLE
I can't manage to execute "Recall a saved layout preset"

### ISSUE THREAD

**Issue by raydjee** [bitfocus/companion-module-extron-smp351#13]
Hey there! First of all thank you very much for sharing this SMP351 module!
Even though I am able to execute the "record" module, along with 3route input to output", nothing is happening when I try to recall a saved layout preset.
Is this a known issue? Or is there a tip in doing it the right way?

Thank you very much!

**Comment by EventReplay** [comment]
@raydjee unfortunatly I have never had access to a unit to do full testing so don't know exactly how it functions using sis commands.
Note from sis commands for layout presets says "Layout Presets (for composite mode only)" does this have anything to do with your issue?

**Comment by peppertechie** [comment]
@raydjee I just started working with Companion, but here is my "test case" if it helps. 

In the SMP-351 GUI go to  
Configuration > Encording&Layout > Layout Preset 
Under layout preset - choose two presets and hit "Recall Preset" then "Recall" in the popup
Take note of what the preview window shows for each preset.

Now in Companion assign "Recall a saved layout preset" to two buttons with the presets you tested in the GMP-351 GUI. 
Test those and look to the GUI preview or HDMI out for results.  
**I do not see the layout preset  change in the GUI when I control it from Companion**, but it does change the output.

**Comment by raydjee** [comment]
Thanks you so much for your comments guys!

Problem solved, I have to admit it was my fault! @EventReplay your module works fine! There is actually an option within the SMP351, to enable or disable layout presets. I was trying to recall a disabled preset. So... I guess the command was well received by the SMP, but nothing happened. Apologies for this dumb fake issue...
@peppertechie I admit the SMP's GUI doesn't give any info on the current layout preset, appart from looking at the preview.

Thank you both for your help!
PS: @EventReplay thanks for the new features!

**Comment by EventReplay** [comment]
Good to hear you solved your issue.
