### ISSUE TITLE
Secondary Stream Feedback Label

### ISSUE THREAD

**Issue by peppertechie** [bitfocus/companion-module-extron-smp351#15]
In the new release of of this module there is a Feedback for 
"Change colors for Secondary RTMP Stream"

In the Extron GUI this stream is referred to as the Backup Stream.  Requesting the feedback information updated from "Secondary" to "Backup" clarity.  

![image](https://user-images.githubusercontent.com/49915015/83923162-ad4d4a00-a74f-11ea-88c2-150995ec9a01.png)

**Comment by EventReplay** [comment]
@peppertechie I can't believe I did this, thought secondary was how the manual reffered to it and makes logical sense, recording ref is secondary! But manual does say Backup! Doh!

I've Amended and submitted a pull request.

**Comment by EventReplay** [comment]
@peppertechie This should now be updated in the latest build. Please check all OK. Thanks

**Comment by peppertechie** [comment]
@EventReplay thank you.  I got caught up in moving the gear.  Everything looks and works great. The labels now follow what the Extron uses.
