### ISSUE TITLE
Password based log-in

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion-module-extron-smp351#2]
Is it possible to add the ability to log-in to Extron's with passwords?

It looks like the protocol for this is on page 151 of [the manual](https://media.extron.com/public/download/files/userman/68-2238-01_A.pdf). There are two modes, user and admin accounts. Is there possibly a way to input the password in the settings page and have it stored?

<img width="1200" alt="Screen Shot 2020-02-10 at 7 30 36 PM" src="https://user-images.githubusercontent.com/50299051/74205205-f4ad4900-4c3b-11ea-93b4-7308187bf833.png">

**Comment by EventReplay** [comment]
I'm sure this should be achieveable, something I would like to add for Extron. When I get time I'll take a look.

**Comment by EventReplay** [comment]
@bryce-seifert I've has a play with my SMX and I think I have a working solution. I've commited the code to the master branch of the SMP. It now needs clearance.

If you could test and confirm the new functions work that would be great.

**Comment by EventReplay** [comment]
Confirmed working but might need a tweak to solve possible feedback issue.
