### ISSUE TITLE
"Extend recording" option

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion-module-extron-smp351#3]
Would it be possible to add the "Extend record time" option?
<img width="558" alt="Screen Shot 2020-02-10 at 7 28 02 PM" src="https://user-images.githubusercontent.com/50299051/74205125-a009ce00-4c3b-11ea-916d-f5fc6635c1a5.png">

Is it documented on [page 163](https://media.extron.com/public/download/files/userman/68-2238-01_A.pdf).

**Comment by EventReplay** [comment]
This looks good to me, I'll ask @JeffreyDavidsz to take a look.

**Comment by EventReplay** [comment]
@bryce-seifert wouldn't take much to add the option to choose duration of extend period instead of a fix 5min.

**Comment by EventReplay** [comment]
@bryce-seifert your extend rec code extends 35mins not 5mins I think, I've corrected but I don't own this unit so can't test.

**Comment by bryce-seifert** [comment]
Ah. I was using this conversion table from the manual. Is that not something that has to be done to replace the [X541]? 
<img width="783" alt="Screen Shot 2020-02-13 at 6 45 46 AM" src="https://user-images.githubusercontent.com/50299051/74436736-8bd8f300-4e2c-11ea-96f2-65dec1d34506.png">

And I agree, I think inputing duration would be easy to implement. I can work on that when I get a chance. The one note for that is that value can only be equal from 1 - 60

**Comment by EventReplay** [comment]
I think case should look like:

		case 'extend_rec':
			cmd = "\x1BE"+opt.duration+"RCDR";
			break;

Given you add the input option duration
Manual I have states X541 = Time  MM (0 to 99 minutes) It simply want that number.

**Comment by EventReplay** [comment]
@bryce-seifert can you confirm pause & extend recording actions work ok please and I'll close this.

**Comment by bryce-seifert** [comment]
This is currently returning error code E13, which the manual states is "Invalid parameter (number is out of range)." Investigating. 

**Update: I think this might have to do with ad hoc vs scheduled recording. Testing later today.**

<img width="460" alt="Screen Shot 2020-02-18 at 11 27 13 AM" src="https://user-images.githubusercontent.com/50299051/74761891-7ad01d80-5242-11ea-8aae-1bf38dd046fd.png">

**Comment by EventReplay** [comment]
@bryce-seifert maybe needs a leading 0 so 05 for 5mins? does say = Time MM.

Let me know and I'll try to fix.

**Comment by bryce-seifert** [comment]
@EventReplay Sorry, forgot to update. The issue was that you can only extend scheduled recordings and I was testing with an ad hoc recording. I fixed this in https://github.com/bitfocus/companion-module-extron-smp351/pull/7 by adding a note about this above the input.
