### ISSUE TITLE
Impossible Connection without password

### ISSUE THREAD

**Issue by Jo-Overlap** [bitfocus/companion-module-extron-smp351#35]
Hi, 
On the Companion 3.1.2 version it's no longer possible to connect an Extron SMP351 if you don't put any password.
Is it possible to fix that problem ?
It's working fine without password on 2.4.2 version.
Thank you for your fantastic job on the companion app, it's such a fantastic tool to use ! :)
Best regards
Jonathan

**Comment by bryce-seifert** [comment]
@Jo-Overlap A fix for this is now available in the latest Companion beta. Let me know fi you still run into issues
