### ISSUE TITLE
SMP 351 stock in “connecting” status

### ISSUE THREAD

**Issue by EnriqueDgago** [bitfocus/companion-module-extron-smp351#37]
Hi! I’ve connected two SMP 351 model to two different companions and I have encounter the same issues, although the input information is correct (IP adresse and password) the SMP stays on connecting status. I can still control the SMP but is not perfect, for exemple, you can still use the record fonction but you have to press several times on the companion button in order for it to work, any ideas on how to fix it?

**Comment by bryce-seifert** [comment]
What version of companion? What version of Extron firmware? Are there any messages in the companion or Extron logs?

**Comment by EnriqueDgago** [comment]
3.1.2 companion, 3.01 firmware version, no error message on SMP log

**Comment by bryce-seifert** [comment]
Interesting. And nothing in companion log either?

Have you tried both the Extron admin and user accounts? 

Also I’m not sure of the differences since I can’t find a change log, but it has been stable for me on SMP firmware 3.06

**Comment by bryce-seifert** [comment]
@EnriqueDgago Any additional details you can provide to the questions above?

**Comment by bryce-seifert** [comment]
@EnriqueDgago Are you still experiencing this issue?

**Comment by bryce-seifert** [comment]
@EnriqueDgago Any updates on if this issue persists?
