### ISSUE TITLE
Button feedback for recording state

### ISSUE THREAD

**Issue by bryce-seifert** [bitfocus/companion-module-extron-smp351#4]
It would be great to know the current recording status as button feedback.

It looks like the Extron provides this info as documented on [page 163 on the manual](https://media.extron.com/public/download/files/userman/68-2238-01_A.pdf).
<img width="798" alt="Screen Shot 2020-02-10 at 7 28 55 PM" src="https://user-images.githubusercontent.com/50299051/74205137-aac46300-4c3b-11ea-93e8-6197a707b437.png">

<img width="677" alt="Screen Shot 2020-02-10 at 10 29 01 AM" src="https://user-images.githubusercontent.com/50299051/74169024-3fa16f00-4bf0-11ea-82d9-a79962d9de09.png">

**Comment by EventReplay** [comment]
I have already done this on the smp111 module and it was confirmed working, I'll take a look.

**Comment by EventReplay** [comment]
@bryce-seifert  I've implemented the same code I did on the SMP111 for record feedback which was confrimed working. It just needs clearance.
Module now sets verbose mode to 3 so will send responses back to companion.
Can you please test ASAP and confirm working.
Many Thanks

**Comment by bryce-seifert** [comment]
I need to work on a password solution or just hard code a password for testing purposes, since all of our Extrons require authentication. But I’d be happy to test it once I get past that hurdle.

**Comment by EventReplay** [comment]
I think it should be straight forward to impliment It's a basic login. I'll have a go.

**Comment by EventReplay** [comment]
@bryce-seifert  Feedback and password login should now be included in the lastest 2.0 build

If you could confirm working or let me know of any issues you encounter. Thank you

**Comment by bryce-seifert** [comment]
@EventReplay Login appears to be working!

Initial look, it doesn't seem feedback is working. I need to set aside some time to properly test that and make sure it's not on my end.

**Comment by EventReplay** [comment]
@bryce-seifert do you have a dev enviroment setup?

To check the units doing what its suppose to I would suggest using wireshark and you should see a return reposonse to a button press to companion of "RcdrY1" Start recording "RcdrY0" Stop recording. If you can't see these then it could be the changes I made to get password to work. It's important that the first command sent sets verbose mode for feedback to work.

**Comment by bryce-seifert** [comment]
Got it. I'll try and find time I can fully take one of our machines out of production early next week to test all of this and report back.

**Comment by EventReplay** [comment]
@bryce-seifert I've done some testing with my SMX and think I've solved the feedback issue, verbose mode wasn't being activated if a password was set.

Just needs confirming. Cheers.

**Comment by bryce-seifert** [comment]
Ok, feedback doesn't appear to work in the latest build. Also, "Recording" has disappeared as a drop down from the feedback menu. <img width="570" alt="Screen Shot 2020-02-18 at 9 21 36 AM" src="https://user-images.githubusercontent.com/50299051/74749725-33409600-5230-11ea-8a82-7ed259b38746.png">

**Comment by bryce-seifert** [comment]
Feedback is confirmed working.

**Comment by bryce-seifert** [comment]
@EventReplay One thing I'm noticing is that feedback doesn't seem to update when 1) first creating the module or 2) disable/enabling the module. It waits for a state change from the Extron. Would it be possible to check the current state whenever the module is created, or enabled?

**Comment by EventReplay** [comment]
@bryce-seifert Makes sense will do.

**Comment by EventReplay** [comment]
@bryce-seifert Try this, add:
		self.socket.write("\x1BYRCDR"+ "\n"); // Request Record Status
to if, should now be:
	if (self.login === false && data.match("Password:")) {
		self.status(self.STATUS_WARNING,'Logging in');
		self.socket.write("\r" +self.config.password+ "\r"); // Enter Password Set
		self.socket.write("\x1BYRCDR"+ "\n"); // Request Record Status
	}
Let me know if that does the trick and I'll update.

**Comment by bryce-seifert** [comment]
Hmm, that doesn't seem to do it. Here's what the log looks like

`  lib/telnet new conn +3ms
  instance:extron-smp351:fnb3k9Nc Connected +0ms
  instance:extron-smp351:fnb3k9Nc 
  instance:extron-smp351:fnb3k9Nc (c) Copyright 2014-2019, Extron Electronics, SMP 351 3G-SDI, V2.11, 60-1324-02
  instance:extron-smp351:fnb3k9Nc Thu, 20 Feb 2020 16:00:49
  instance:extron-smp351:fnb3k9Nc  +99ms
  lib/telnet sending 5 bytes to 172.16.165.9 23 +100ms
  lib/telnet sending 3 bytes to 172.16.165.9 23 +0ms
  instance:extron-smp351:fnb3k9Nc data nologin 
(c) Copyright 2014-2019, Extron Electronics, SMP 351 3G-SDI, V2.11, 60-1324-02
Thu, 20 Feb 2020 16:00:49
 +0ms
  instance:extron-smp351:fnb3k9Nc 
  instance:extron-smp351:fnb3k9Nc Password: +7ms
  lib/telnet sending 12 bytes to 172.16.165.9 23 +7ms
  lib/telnet sending 7 bytes to 172.16.165.9 23 +0ms
  instance:extron-smp351:fnb3k9Nc data nologin 
Password: +0ms
  lib/variable Variable $(internal:time_hms) is "16:0:49" +462ms
  instance:extron-smp351:fnb3k9Nc 
  instance:extron-smp351:fnb3k9Nc Password: +1s
  lib/telnet sending 12 bytes to 172.16.165.9 23 +1s
  lib/telnet sending 7 bytes to 172.16.165.9 23 +0ms
  instance:extron-smp351:fnb3k9Nc data nologin 
Password: +1ms
  lib/variable Variable $(internal:time_hms) is "16:0:50" +1s
  lib/variable Variable $(internal:time_hms) is "16:0:51" +1s
  instance:extron-smp351:fnb3k9Nc 
  instance:extron-smp351:fnb3k9Nc Password: +1s
  lib/telnet sending 12 bytes to 172.16.165.9 23 +1s
  lib/telnet sending 7 bytes to 172.16.165.9 23 +0ms
  instance:extron-smp351:fnb3k9Nc data nologin 
Password: +1ms
  instance:extron-smp351:fnb3k9Nc 
  instance:extron-smp351:fnb3k9Nc Password: +106ms
  lib/telnet sending 12 bytes to 172.16.165.9 23 +108ms
  lib/telnet sending 7 bytes to 172.16.165.9 23 +20ms
  instance:extron-smp351:fnb3k9Nc data nologin 
Password: +22ms
  instance:extron-smp351:fnb3k9Nc 
  instance:extron-smp351:fnb3k9Nc Login Administrator
  instance:extron-smp351:fnb3k9Nc  +550ms
  lib/telnet sending 5 bytes to 172.16.165.9 23 +550ms
  lib/variable Variable $(internal:instance_warns) is "0" +680ms
  lib/variable Variable $(internal:instance_oks) is "2" +2ms
  instance:extron-smp351:fnb3k9Nc logged in +4ms
  instance:extron-smp351:fnb3k9Nc data nologin 
Login Administrator
 +0ms
  instance:extron-smp351:fnb3k9Nc 0
  instance:extron-smp351:fnb3k9Nc E10
  instance:extron-smp351:fnb3k9Nc  +96ms
  instance:extron-smp351:fnb3k9Nc data nologin 0
E10
 +0ms
  instance:extron-smp351:fnb3k9Nc 0
  instance:extron-smp351:fnb3k9Nc E10
  instance:extron-smp351:fnb3k9Nc  +100ms
  instance:extron-smp351:fnb3k9Nc data nologin 0
E10
 +0ms
  lib/variable Variable $(internal:time_hms) is "16:0:52" +320ms
  instance:extron-smp351:fnb3k9Nc 0
  instance:extron-smp351:fnb3k9Nc  +401ms
  instance:extron-smp351:fnb3k9Nc data nologin 0
 +0ms
  instance:extron-smp351:fnb3k9Nc E10
  instance:extron-smp351:fnb3k9Nc  +0ms
  instance:extron-smp351:fnb3k9Nc data nologin E10
 +0ms
  instance:extron-smp351:fnb3k9Nc 0
  instance:extron-smp351:fnb3k9Nc  +204ms
  instance:extron-smp351:fnb3k9Nc data nologin 0
 +1ms
  instance:extron-smp351:fnb3k9Nc Vrb3
  instance:extron-smp351:fnb3k9Nc  +3ms
  instance:extron-smp351:fnb3k9Nc data nologin Vrb3
 +0ms
  lib/variable Variable $(internal:time_hms) is "16:0:53" +1s
  lib/variable Variable $(internal:time_hms) is "16:0:54" +1s
  lib/variable Variable $(internal:time_hms) is "16:0:55" +1s
  lib/db db_save begin +8s
  lib/db db_save written +4ms
  lib/db db_save renamed +0ms
  lib/variable Variable $(internal:time_hms) is "16:0:56" +1s
  lib/preview handlePreview() false undefined +10s
  lib/preview socket yL_IdWI08Ko9oyiLAAAB removed preview listener +0ms
  lib/variable Variable $(internal:time_hms) is "16:0:57" +1s
  lib/preview handlePreview() 1 19 +998ms
  lib/preview socket yL_IdWI08Ko9oyiLAAAB added preview listener for 1, 19 +0ms
`

**Comment by EventReplay** [comment]
Can you do a test with hercules or packet sender?
It looks likes it's only responding with a single number 0,1,2. By setting Verbose 3 I was expecting a response RcdrY(0,1,2).
Use one of above programs, Login, enter password, set Verbose 3 mode, request status
What response do you get?

**Comment by EventReplay** [comment]
@bryce-seifert I currently use https://www.hw-group.com/files/download/sw/version/hercules_3-2-8.exe for testing, but https://packetsender.com/ or Extron Dataviewer should be fine.

**Comment by EventReplay** [comment]
@bryce-seifert Maybe try this:
Instead of adding to if add to else if so now
	// Match login sucess response from unit.
	else if (self.login === false && data.match("Login")) {
		self.login = true;
		self.socket.write("\x1B3CV"+ "\r"); // Set Verbose mode to 3
		self.socket.write("\x1BYRCDR"+ "\n"); // Request Record Status
		self.status(self.STATUS_OK);
		debug("logged in");
	}

**Comment by bryce-seifert** [comment]
Yep! That did the trick. It's now correctly returning 
`0ms
  instance:extron-smp351:fnb3k9Nc Vrb3
  instance:extron-smp351:fnb3k9Nc  +12ms
  instance:extron-smp351:fnb3k9Nc data nologin Vrb3
 +0ms
  instance:extron-smp351:fnb3k9Nc RcdrY0
  instance:extron-smp351:fnb3k9Nc  +90ms
  instance:extron-smp351:fnb3k9Nc recording change +1ms
`

And the button feedback is updating for both newly created modules, and for when the module it enabled/disabled. Thank you so much.

**Comment by EventReplay** [comment]
Great news, Thank you for testing & feedback.

I did think about adding the record status request to the heartbeat and reducing the heartbeat time interval to 10 seconds as an additional measure but I feel this would create unwanted/unneeded extra network traffic.
